#$L$
# Copyright (C) 2014 Ridgerun (http://www.ridgerun.com). 
##$L$

FETCHER_NO_DOWNLOAD=yes
LIBRARIES= /usr/lib/gstreamer-0.10/libgstbufferpartitioner.so

include $(DEVDIR)/bsp/classes/rrsdk.class
include $(DEVDIR)/bsp/classes/autotools.class

